version: "3.8"

services:
  mongodb:
    image: sbis_mongo
    container_name: sbis_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adm1n
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://admin:adm1n@mongodb:27017'
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
    depends_on:
      - mongodb