spring:
  application:
    name: SBISserv
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: adm1n
      database: sbis_db
      host: ${DB_HOST}
      port: 27017
rsa:
  private-key: /secrets/private.key
  public-key: /secrets/public.key