db.createCollection("clients")
db.clients.insertMany(
[{
  "clientName": "u123456",
  "clientSecret": "$2a$10$IKOFdQ6sXBDieTb5I6FNJ.JgxJTRxqkJ17IpmtSd9JIu5/JTWkJ7e"
}]
)
db.createCollection("points")
db.points.insertMany(
[{
  "id": 170,
  "name": "Магазин Алкотека",
  "phone": "+79521223355",
  "address": "ул. Туполева"
},
{
  "id": 3655,
  "name": "Магазин Алкогольия",
  "phone": "+79521223355",
  "address": "ул. Комарова"
}]
)

db.createCollection("pricelists")
db.pricelists.insertMany(
[{
  "id": 65,
  "name": "Прайс-лист по умолчанию"
},
{
  "id": 70,
  "name": "Новогодний прайс-лист"
}
])

db.createCollection("nomenclrs")
db.nomenclrs.insertMany(
[{
  "pointId": 170,
  "priceListId": 70,
  "prods": [
    {
      "name": "Пиво",
      "description": null,
      "isParent": true,
      "hierarchicalId": 32,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Фруктовые напитки б/а",
      "description": null,
      "isParent": true,
      "hierarchicalId": 33,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Безалкогольные",
      "description": null,
      "isParent": true,
      "hierarchicalId": 34,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Напиток б/а бархатный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 35,
      "hierarchicalParent": 32,
      "externalId": "c171be53-c651-4102-a4a0-4581946d8a91",
      "cost": 110,
      "unit": "кг",
      "balance": 65.8,
      "images": null,
    },
    {
      "name": "Бланш Бир нефильтрованное",
      "description": null,
      "isParent": null,
      "hierarchicalId": 36,
      "hierarchicalParent": 32,
      "externalId": "72485158-6698-4a8f-abd3-48d2eec5beb9",
      "cost": 135,
      "unit": "кг",
      "balance": 27,
      "images": null,
    },
    {
      "name": "Напиток б/а  домашний",
      "description": null,
      "isParent": null,
      "hierarchicalId": 37,
      "hierarchicalParent": 32,
      "externalId": "19fae502-e8a9-499d-a03d-849c259b2b15",
      "cost": 103,
      "unit": "кг",
      "balance": 82.7,
      "images": null,
    },
    {
      "name": "Жигулевское особое светлое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 38,
      "hierarchicalParent": 32,
      "externalId": "687d481a-04a4-4ad3-bd69-3dbdb678eae2",
      "cost": 100,
      "unit": "кг",
      "balance": 138.5,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 39,
      "hierarchicalParent": 32,
      "externalId": "d4e06a01-4712-49cb-85b8-53ffc20432da",
      "cost": 115,
      "unit": "кг",
      "balance": 89.2,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий",
      "description": null,
      "isParent": null,
      "hierarchicalId": 40,
      "hierarchicalParent": 32,
      "externalId": "74a87946-0d4e-4282-af33-17a735e57bf7",
      "cost": 108,
      "unit": "кг",
      "balance": 59,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий н/ф",
      "description": null,
      "isParent": null,
      "hierarchicalId": 41,
      "hierarchicalParent": 32,
      "externalId": "2476fa77-d2f7-42ee-b349-2623dce65230",
      "cost": 108,
      "unit": "кг",
      "balance": 95.7,
      "images": null,
    },
    {
      "name": "Напиток б/а СССР",
      "description": null,
      "isParent": null,
      "hierarchicalId": 42,
      "hierarchicalParent": 32,
      "externalId": "3bef03e6-84a5-47e4-9ec0-7651f6603b6b",
      "cost": 108,
      "unit": "кг",
      "balance": 72.3,
      "images": null,
    },
    {
      "name": "Чешский кабанчик пшеничное особое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 43,
      "hierarchicalParent": 32,
      "externalId": "05aabb98-087f-4a53-bf2c-207ac8883544",
      "cost": 125,
      "unit": "кг",
      "balance": 91.75,
      "images": null,
    },
    {
      "name": "Напиток б/а чешский",
      "description": null,
      "isParent": null,
      "hierarchicalId": 44,
      "hierarchicalParent": 32,
      "externalId": "54d474ef-6d2d-42b8-8c8c-6887c9936ff5",
      "cost": 108,
      "unit": "кг",
      "balance": 129.3,
      "images": null,
    },
    {
      "name": "Портер №6",
      "description": null,
      "isParent": null,
      "hierarchicalId": 45,
      "hierarchicalParent": 32,
      "externalId": "7f0317a0-6355-4dc5-9e18-405d6acd243a",
      "cost": 140,
      "unit": "л",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напиток б/а Блэк беар",
      "description": null,
      "isParent": null,
      "hierarchicalId": 46,
      "hierarchicalParent": 32,
      "externalId": "b7ea3218-2b04-4a88-8255-63ec3af1a391",
      "cost": 145,
      "unit": "кг",
      "balance": 4.1,
      "images": null,
    },
    {
      "name": "Напиток б/а Безумный монах",
      "description": null,
      "isParent": null,
      "hierarchicalId": 47,
      "hierarchicalParent": 32,
      "externalId": "d35da950-7c49-4aab-85fd-d0306eaebef0",
      "cost": 145,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напиток б/а бойлерный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 48,
      "hierarchicalParent": 32,
      "externalId": "7237ff6d-7d69-460a-b986-b356ae5e32be",
      "cost": 110,
      "unit": "шт",
      "balance": 77,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль красный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 49,
      "hierarchicalParent": 32,
      "externalId": "428a8c9d-4f25-419d-b2dc-b1ff845745a7",
      "cost": 120,
      "unit": "кг",
      "balance": 51.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а гранат",
      "description": null,
      "isParent": null,
      "hierarchicalId": 50,
      "hierarchicalParent": 33,
      "externalId": "672f18a6-c084-4b7e-8432-1be6eb46303d",
      "cost": 115,
      "unit": "кг",
      "balance": 52.25,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а клюква с брусникой",
      "description": null,
      "isParent": null,
      "hierarchicalId": 51,
      "hierarchicalParent": 33,
      "externalId": "baadfce9-1400-4b33-b98a-d566efc4eea7",
      "cost": 115,
      "unit": "кг",
      "balance": 75.9,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а медовый",
      "description": null,
      "isParent": null,
      "hierarchicalId": 52,
      "hierarchicalParent": 33,
      "externalId": "f1fb63aa-52d8-4a9f-ae62-4384d44ef069",
      "cost": 115,
      "unit": "кг",
      "balance": 74.65,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом апероль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 53,
      "hierarchicalParent": 33,
      "externalId": "20305c85-358d-4b88-a632-28b6e2db53ae",
      "cost": 115,
      "unit": "кг",
      "balance": 34.4,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом асти роуз",
      "description": null,
      "isParent": null,
      "hierarchicalId": 54,
      "hierarchicalParent": 33,
      "externalId": "ea0cdecf-1896-4d66-b46f-758a31dbdf92",
      "cost": 115,
      "unit": "кг",
      "balance": 60.3,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом голубой лагуны",
      "description": null,
      "isParent": null,
      "hierarchicalId": 55,
      "hierarchicalParent": 33,
      "externalId": "9cb137dc-b9ff-4170-bcd9-d8024712b762",
      "cost": 115,
      "unit": "кг",
      "balance": 101.025,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом колы",
      "description": null,
      "isParent": null,
      "hierarchicalId": 56,
      "hierarchicalParent": 33,
      "externalId": "5d9c3596-0a06-4a60-8ed7-406acd6f80e6",
      "cost": 115,
      "unit": "кг",
      "balance": 65,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом мохито",
      "description": null,
      "isParent": null,
      "hierarchicalId": 57,
      "hierarchicalParent": 33,
      "externalId": "a4fbd31f-e6ad-41ad-aa0a-399d34169530",
      "cost": 115,
      "unit": "кг",
      "balance": 44.25,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом пина колады",
      "description": null,
      "isParent": null,
      "hierarchicalId": 58,
      "hierarchicalParent": 33,
      "externalId": "60af5b46-2996-4bf1-8476-2f73cdd23c5a",
      "cost": 115,
      "unit": "кг",
      "balance": 48.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом сакуры",
      "description": null,
      "isParent": null,
      "hierarchicalId": 59,
      "hierarchicalParent": 33,
      "externalId": "7ed7e67f-9cbf-47a3-bf93-9809d443e5ab",
      "cost": 115,
      "unit": "кг",
      "balance": 96.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом спелой маракуйи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 60,
      "hierarchicalParent": 33,
      "externalId": "58514c3c-5299-4f11-b81e-04665e38bf02",
      "cost": 115,
      "unit": "кг",
      "balance": 79.4,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом яблоко",
      "description": null,
      "isParent": null,
      "hierarchicalId": 61,
      "hierarchicalParent": 33,
      "externalId": "2c8e242c-12d1-4a66-93b4-b701bd98cab5",
      "cost": 115,
      "unit": "кг",
      "balance": 35.65,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а манговый смузи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 62,
      "hierarchicalParent": 33,
      "externalId": "c95a4720-494c-4d09-a73f-cbf6e4314273",
      "cost": 115,
      "unit": "кг",
      "balance": 64.65,
      "images": null,
    },
    {
      "name": "Буратино",
      "description": null,
      "isParent": null,
      "hierarchicalId": 63,
      "hierarchicalParent": 34,
      "externalId": "622af6d0-9f05-42e5-8883-0c99cf0c1050",
      "cost": 93,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Лимонад",
      "description": null,
      "isParent": null,
      "hierarchicalId": 64,
      "hierarchicalParent": 34,
      "externalId": "5a643205-cdb5-42bb-86b2-93413abec51a",
      "cost": 108,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напитки  дюшес",
      "description": null,
      "isParent": null,
      "hierarchicalId": 65,
      "hierarchicalParent": 34,
      "externalId": "017fb7ab-1139-4e19-9513-873307ee8d9a",
      "cost": 60,
      "unit": "кг",
      "balance": 48.15,
      "images": null,
    },
    {
      "name": "Напитки  тархун",
      "description": null,
      "isParent": null,
      "hierarchicalId": 66,
      "hierarchicalParent": 34,
      "externalId": "1cb82518-c1c6-4197-b6cf-b428df109eca",
      "cost": 75,
      "unit": "кг",
      "balance": 52.7,
      "images": null,
    },
    {
      "name": "Квас",
      "description": null,
      "isParent": null,
      "hierarchicalId": 67,
      "hierarchicalParent": 34,
      "externalId": "d61fd7a9-8a7b-4355-9b20-b2920ff75f6f",
      "cost": 60,
      "unit": "л",
      "balance": 87.75,
      "images": null,
    },
    {
      "name": "Экстро Ситро",
      "description": null,
      "isParent": null,
      "hierarchicalId": 68,
      "hierarchicalParent": 34,
      "externalId": "565fb58b-e10d-4039-ae2b-23e88d5629ff",
      "cost": 60,
      "unit": "кг",
      "balance": 0,
      "images": null,
      "_id": {
        "$oid": "6304446951b9be46c72955a2"
      }
    }
  ]
},
{
  "pointId": 3655,
  "priceListId": 70,
  "prods": [
    {
      "name": "Пиво",
      "description": null,
      "isParent": true,
      "hierarchicalId": 32,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Фруктовые напитки б/а",
      "description": null,
      "isParent": true,
      "hierarchicalId": 33,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Безалкогольные",
      "description": null,
      "isParent": true,
      "hierarchicalId": 34,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Напиток б/а бархатный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 35,
      "hierarchicalParent": 32,
      "externalId": "c171be53-c651-4102-a4a0-4581946d8a91",
      "cost": 110,
      "unit": "кг",
      "balance": 30.65,
      "images": null,
    },
    {
      "name": "Бланш Бир нефильтрованное",
      "description": null,
      "isParent": null,
      "hierarchicalId": 36,
      "hierarchicalParent": 32,
      "externalId": "72485158-6698-4a8f-abd3-48d2eec5beb9",
      "cost": 135,
      "unit": "кг",
      "balance": 95.45,
      "images": null,
    },
    {
      "name": "Напиток б/а  домашний",
      "description": null,
      "isParent": null,
      "hierarchicalId": 37,
      "hierarchicalParent": 32,
      "externalId": "19fae502-e8a9-499d-a03d-849c259b2b15",
      "cost": 103,
      "unit": "кг",
      "balance": 18.1,
      "images": null,
    },
    {
      "name": "Жигулевское особое светлое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 38,
      "hierarchicalParent": 32,
      "externalId": "687d481a-04a4-4ad3-bd69-3dbdb678eae2",
      "cost": 100,
      "unit": "кг",
      "balance": 68.3,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 39,
      "hierarchicalParent": 32,
      "externalId": "d4e06a01-4712-49cb-85b8-53ffc20432da",
      "cost": 115,
      "unit": "кг",
      "balance": 65.6,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий",
      "description": null,
      "isParent": null,
      "hierarchicalId": 40,
      "hierarchicalParent": 32,
      "externalId": "74a87946-0d4e-4282-af33-17a735e57bf7",
      "cost": 108,
      "unit": "кг",
      "balance": 47.3,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий н/ф",
      "description": null,
      "isParent": null,
      "hierarchicalId": 41,
      "hierarchicalParent": 32,
      "externalId": "2476fa77-d2f7-42ee-b349-2623dce65230",
      "cost": 108,
      "unit": "кг",
      "balance": 64.05,
      "images": null,
    },
    {
      "name": "Напиток б/а СССР",
      "description": null,
      "isParent": null,
      "hierarchicalId": 42,
      "hierarchicalParent": 32,
      "externalId": "3bef03e6-84a5-47e4-9ec0-7651f6603b6b",
      "cost": 108,
      "unit": "кг",
      "balance": 29,
      "images": null,
    },
    {
      "name": "Чешский кабанчик пшеничное особое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 43,
      "hierarchicalParent": 32,
      "externalId": "05aabb98-087f-4a53-bf2c-207ac8883544",
      "cost": 125,
      "unit": "кг",
      "balance": 95.35,
      "images": null,
    },
    {
      "name": "Напиток б/а чешский",
      "description": null,
      "isParent": null,
      "hierarchicalId": 44,
      "hierarchicalParent": 32,
      "externalId": "54d474ef-6d2d-42b8-8c8c-6887c9936ff5",
      "cost": 108,
      "unit": "кг",
      "balance": 43.2,
      "images": null,
    },
    {
      "name": "Портер №6",
      "description": null,
      "isParent": null,
      "hierarchicalId": 45,
      "hierarchicalParent": 32,
      "externalId": "7f0317a0-6355-4dc5-9e18-405d6acd243a",
      "cost": 140,
      "unit": "л",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напиток б/а Блэк беар",
      "description": null,
      "isParent": null,
      "hierarchicalId": 46,
      "hierarchicalParent": 32,
      "externalId": "b7ea3218-2b04-4a88-8255-63ec3af1a391",
      "cost": 145,
      "unit": "кг",
      "balance": 0.3,
      "images": null,
    },
    {
      "name": "Напиток б/а Безумный монах",
      "description": null,
      "isParent": null,
      "hierarchicalId": 47,
      "hierarchicalParent": 32,
      "externalId": "d35da950-7c49-4aab-85fd-d0306eaebef0",
      "cost": 145,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напиток б/а бойлерный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 48,
      "hierarchicalParent": 32,
      "externalId": "7237ff6d-7d69-460a-b986-b356ae5e32be",
      "cost": 110,
      "unit": "шт",
      "balance": 31.9,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль красный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 49,
      "hierarchicalParent": 32,
      "externalId": "428a8c9d-4f25-419d-b2dc-b1ff845745a7",
      "cost": 120,
      "unit": "кг",
      "balance": 46.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а гранат",
      "description": null,
      "isParent": null,
      "hierarchicalId": 50,
      "hierarchicalParent": 33,
      "externalId": "672f18a6-c084-4b7e-8432-1be6eb46303d",
      "cost": 115,
      "unit": "кг",
      "balance": 33.95,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а клюква с брусникой",
      "description": null,
      "isParent": null,
      "hierarchicalId": 51,
      "hierarchicalParent": 33,
      "externalId": "baadfce9-1400-4b33-b98a-d566efc4eea7",
      "cost": 115,
      "unit": "кг",
      "balance": 49.55,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а медовый",
      "description": null,
      "isParent": null,
      "hierarchicalId": 52,
      "hierarchicalParent": 33,
      "externalId": "f1fb63aa-52d8-4a9f-ae62-4384d44ef069",
      "cost": 115,
      "unit": "кг",
      "balance": 75.45,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом апероль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 53,
      "hierarchicalParent": 33,
      "externalId": "20305c85-358d-4b88-a632-28b6e2db53ae",
      "cost": 115,
      "unit": "кг",
      "balance": 56.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом асти роуз",
      "description": null,
      "isParent": null,
      "hierarchicalId": 54,
      "hierarchicalParent": 33,
      "externalId": "ea0cdecf-1896-4d66-b46f-758a31dbdf92",
      "cost": 115,
      "unit": "кг",
      "balance": 40.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом голубой лагуны",
      "description": null,
      "isParent": null,
      "hierarchicalId": 55,
      "hierarchicalParent": 33,
      "externalId": "9cb137dc-b9ff-4170-bcd9-d8024712b762",
      "cost": 115,
      "unit": "кг",
      "balance": 66.65,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом колы",
      "description": null,
      "isParent": null,
      "hierarchicalId": 56,
      "hierarchicalParent": 33,
      "externalId": "5d9c3596-0a06-4a60-8ed7-406acd6f80e6",
      "cost": 115,
      "unit": "кг",
      "balance": 55.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом мохито",
      "description": null,
      "isParent": null,
      "hierarchicalId": 57,
      "hierarchicalParent": 33,
      "externalId": "a4fbd31f-e6ad-41ad-aa0a-399d34169530",
      "cost": 115,
      "unit": "кг",
      "balance": 43.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом пина колады",
      "description": null,
      "isParent": null,
      "hierarchicalId": 58,
      "hierarchicalParent": 33,
      "externalId": "60af5b46-2996-4bf1-8476-2f73cdd23c5a",
      "cost": 115,
      "unit": "кг",
      "balance": 25.2,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом сакуры",
      "description": null,
      "isParent": null,
      "hierarchicalId": 59,
      "hierarchicalParent": 33,
      "externalId": "7ed7e67f-9cbf-47a3-bf93-9809d443e5ab",
      "cost": 115,
      "unit": "кг",
      "balance": 83.65,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом спелой маракуйи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 60,
      "hierarchicalParent": 33,
      "externalId": "58514c3c-5299-4f11-b81e-04665e38bf02",
      "cost": 115,
      "unit": "кг",
      "balance": 62.35,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом яблоко",
      "description": null,
      "isParent": null,
      "hierarchicalId": 61,
      "hierarchicalParent": 33,
      "externalId": "2c8e242c-12d1-4a66-93b4-b701bd98cab5",
      "cost": 115,
      "unit": "кг",
      "balance": 45.75,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а манговый смузи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 62,
      "hierarchicalParent": 33,
      "externalId": "c95a4720-494c-4d09-a73f-cbf6e4314273",
      "cost": 115,
      "unit": "кг",
      "balance": 67.35,
      "images": null,
    },
    {
      "name": "Буратино",
      "description": null,
      "isParent": null,
      "hierarchicalId": 63,
      "hierarchicalParent": 34,
      "externalId": "622af6d0-9f05-42e5-8883-0c99cf0c1050",
      "cost": 93,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Лимонад",
      "description": null,
      "isParent": null,
      "hierarchicalId": 64,
      "hierarchicalParent": 34,
      "externalId": "5a643205-cdb5-42bb-86b2-93413abec51a",
      "cost": 108,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Напитки  дюшес",
      "description": null,
      "isParent": null,
      "hierarchicalId": 65,
      "hierarchicalParent": 34,
      "externalId": "017fb7ab-1139-4e19-9513-873307ee8d9a",
      "cost": 60,
      "unit": "кг",
      "balance": 18.5,
      "images": null,
    },
    {
      "name": "Напитки  тархун",
      "description": null,
      "isParent": null,
      "hierarchicalId": 66,
      "hierarchicalParent": 34,
      "externalId": "1cb82518-c1c6-4197-b6cf-b428df109eca",
      "cost": 75,
      "unit": "кг",
      "balance": 45,
      "images": null,
    },
    {
      "name": "Квас",
      "description": null,
      "isParent": null,
      "hierarchicalId": 67,
      "hierarchicalParent": 34,
      "externalId": "d61fd7a9-8a7b-4355-9b20-b2920ff75f6f",
      "cost": 60,
      "unit": "л",
      "balance": 60.2,
      "images": null,
    },
    {
      "name": "Экстро Ситро",
      "description": null,
      "isParent": null,
      "hierarchicalId": 68,
      "hierarchicalParent": 34,
      "externalId": "565fb58b-e10d-4039-ae2b-23e88d5629ff",
      "cost": 60,
      "unit": "кг",
      "balance": -0.95,
      "images": null,
    }
  ]
},
{
  "pointId": 170,
  "priceListId": 65,
  "prods": [
    {
      "name": "Пиво",
      "description": null,
      "isParent": true,
      "hierarchicalId": 32,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Фруктовые напитки б/а",
      "description": null,
      "isParent": true,
      "hierarchicalId": 33,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Безалкогольные",
      "description": null,
      "isParent": true,
      "hierarchicalId": 34,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Напиток б/а бархатный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 35,
      "hierarchicalParent": 32,
      "externalId": "c171be53-c651-4102-a4a0-4581946d8a91",
      "cost": 110,
      "unit": "кг",
      "balance": 98.7,
      "images": null,
    },
    {
      "name": "Напиток Бланш Бир нефильтрованное",
      "description": null,
      "isParent": null,
      "hierarchicalId": 36,
      "hierarchicalParent": 32,
      "externalId": "72485158-6698-4a8f-abd3-48d2eec5beb9",
      "cost": 135,
      "unit": "кг",
      "balance": 143.5,
      "images": null,
    },
    {
      "name": "Напиток б/а  домашний",
      "description": null,
      "isParent": null,
      "hierarchicalId": 37,
      "hierarchicalParent": 32,
      "externalId": "19fae502-e8a9-499d-a03d-849c259b2b15",
      "cost": 103,
      "unit": "кг",
      "balance": 45.9,
      "images": null,
    },
    {
      "name": "Напиток Жигулевское особое светлое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 38,
      "hierarchicalParent": 32,
      "externalId": "687d481a-04a4-4ad3-bd69-3dbdb678eae2",
      "cost": 100,
      "unit": "кг",
      "balance": 754.5,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 39,
      "hierarchicalParent": 32,
      "externalId": "d4e06a01-4712-49cb-85b8-53ffc20432da",
      "cost": 115,
      "unit": "кг",
      "balance": 134.85,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий",
      "description": null,
      "isParent": null,
      "hierarchicalId": 40,
      "hierarchicalParent": 32,
      "externalId": "74a87946-0d4e-4282-af33-17a735e57bf7",
      "cost": 108,
      "unit": "кг",
      "balance": 116.45,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий н/ф",
      "description": null,
      "isParent": null,
      "hierarchicalId": 41,
      "hierarchicalParent": 32,
      "externalId": "2476fa77-d2f7-42ee-b349-2623dce65230",
      "cost": 108,
      "unit": "кг",
      "balance": 83.6,
      "images": null,
    },
    {
      "name": "Напиток б/а СССР",
      "description": null,
      "isParent": null,
      "hierarchicalId": 42,
      "hierarchicalParent": 32,
      "externalId": "3bef03e6-84a5-47e4-9ec0-7651f6603b6b",
      "cost": 108,
      "unit": "кг",
      "balance": 116.5,
      "images": null,
    },
    {
      "name": "Напиток Чешский кабанчик пшеничное особое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 43,
      "hierarchicalParent": 32,
      "externalId": "05aabb98-087f-4a53-bf2c-207ac8883544",
      "cost": 125,
      "unit": "кг",
      "balance": 41.85,
      "images": null,
    },
    {
      "name": "Напиток б/а чешский",
      "description": null,
      "isParent": null,
      "hierarchicalId": 44,
      "hierarchicalParent": 32,
      "externalId": "54d474ef-6d2d-42b8-8c8c-6887c9936ff5",
      "cost": 108,
      "unit": "кг",
      "balance": 186.35,
      "images": null,
    },
    {
      "name": "Напиток б/а Блэк беар",
      "description": null,
      "isParent": null,
      "hierarchicalId": 46,
      "hierarchicalParent": 32,
      "externalId": "b7ea3218-2b04-4a88-8255-63ec3af1a391",
      "cost": 145,
      "unit": "кг",
      "balance": 1.8,
      "images": null,
    },
    {
      "name": "Напиток б/а бойлерный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 48,
      "hierarchicalParent": 32,
      "externalId": "7237ff6d-7d69-460a-b986-b356ae5e32be",
      "cost": 110,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а гранат",
      "description": null,
      "isParent": null,
      "hierarchicalId": 50,
      "hierarchicalParent": 33,
      "externalId": "672f18a6-c084-4b7e-8432-1be6eb46303d",
      "cost": 115,
      "unit": "кг",
      "balance": 110.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а клюква с брусникой",
      "description": null,
      "isParent": null,
      "hierarchicalId": 51,
      "hierarchicalParent": 33,
      "externalId": "baadfce9-1400-4b33-b98a-d566efc4eea7",
      "cost": 115,
      "unit": "кг",
      "balance": 112.25,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом апероль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 53,
      "hierarchicalParent": 33,
      "externalId": "20305c85-358d-4b88-a632-28b6e2db53ae",
      "cost": 115,
      "unit": "кг",
      "balance": 31.9,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом асти роуз",
      "description": null,
      "isParent": null,
      "hierarchicalId": 54,
      "hierarchicalParent": 33,
      "externalId": "ea0cdecf-1896-4d66-b46f-758a31dbdf92",
      "cost": 115,
      "unit": "кг",
      "balance": 70.35,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом голубой лагуны",
      "description": null,
      "isParent": null,
      "hierarchicalId": 55,
      "hierarchicalParent": 33,
      "externalId": "9cb137dc-b9ff-4170-bcd9-d8024712b762",
      "cost": 115,
      "unit": "кг",
      "balance": 85.45,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом колы",
      "description": null,
      "isParent": null,
      "hierarchicalId": 56,
      "hierarchicalParent": 33,
      "externalId": "5d9c3596-0a06-4a60-8ed7-406acd6f80e6",
      "cost": 115,
      "unit": "кг",
      "balance": 139.6,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом мохито",
      "description": null,
      "isParent": null,
      "hierarchicalId": 57,
      "hierarchicalParent": 33,
      "externalId": "a4fbd31f-e6ad-41ad-aa0a-399d34169530",
      "cost": 115,
      "unit": "кг",
      "balance": 80.1,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом пина колады",
      "description": null,
      "isParent": null,
      "hierarchicalId": 58,
      "hierarchicalParent": 33,
      "externalId": "60af5b46-2996-4bf1-8476-2f73cdd23c5a",
      "cost": 115,
      "unit": "кг",
      "balance": 57.55,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом сакуры",
      "description": null,
      "isParent": null,
      "hierarchicalId": 59,
      "hierarchicalParent": 33,
      "externalId": "7ed7e67f-9cbf-47a3-bf93-9809d443e5ab",
      "cost": 115,
      "unit": "кг",
      "balance": 77.15,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом спелой маракуйи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 60,
      "hierarchicalParent": 33,
      "externalId": "58514c3c-5299-4f11-b81e-04665e38bf02",
      "cost": 115,
      "unit": "кг",
      "balance": 108.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом яблоко",
      "description": null,
      "isParent": null,
      "hierarchicalId": 61,
      "hierarchicalParent": 33,
      "externalId": "2c8e242c-12d1-4a66-93b4-b701bd98cab5",
      "cost": 115,
      "unit": "кг",
      "balance": 32.2,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а манговый смузи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 62,
      "hierarchicalParent": 33,
      "externalId": "c95a4720-494c-4d09-a73f-cbf6e4314273",
      "cost": 115,
      "unit": "кг",
      "balance": 95.8,
      "images": null,
    },
    {
      "name": "Напиток  дюшес",
      "description": null,
      "isParent": null,
      "hierarchicalId": 65,
      "hierarchicalParent": 34,
      "externalId": "017fb7ab-1139-4e19-9513-873307ee8d9a",
      "cost": 60,
      "unit": "кг",
      "balance": 78.45,
      "images": null,
    },
    {
      "name": "Напиток  тархун",
      "description": null,
      "isParent": null,
      "hierarchicalId": 66,
      "hierarchicalParent": 34,
      "externalId": "1cb82518-c1c6-4197-b6cf-b428df109eca",
      "cost": 75,
      "unit": "кг",
      "balance": 145.75,
      "images": null,
    },
    {
      "name": "Напиток Квас",
      "description": null,
      "isParent": null,
      "hierarchicalId": 67,
      "hierarchicalParent": 34,
      "externalId": "d61fd7a9-8a7b-4355-9b20-b2920ff75f6f",
      "cost": 60,
      "unit": "л",
      "balance": 53.35,
      "images": null,
    },
    {
      "name": "Напиток Экстро Ситро",
      "description": null,
      "isParent": null,
      "hierarchicalId": 68,
      "hierarchicalParent": 34,
      "externalId": "565fb58b-e10d-4039-ae2b-23e88d5629ff",
      "cost": 60,
      "unit": "кг",
      "balance": 35.75,
      "images": null,
    }
  ]
},
{
  "pointId": 3655,
  "priceListId": 65,
  "prods": [
    {
      "name": "Пиво",
      "description": null,
      "isParent": true,
      "hierarchicalId": 32,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Фруктовые напитки б/а",
      "description": null,
      "isParent": true,
      "hierarchicalId": 33,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Безалкогольные",
      "description": null,
      "isParent": true,
      "hierarchicalId": 34,
      "hierarchicalParent": null,
      "externalId": null,
      "cost": null,
      "unit": null,
      "balance": null,
      "images": null,
    },
    {
      "name": "Напиток б/а бархатный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 35,
      "hierarchicalParent": 32,
      "externalId": "c171be53-c651-4102-a4a0-4581946d8a91",
      "cost": 110,
      "unit": "кг",
      "balance": 55.15,
      "images": null,
    },
    {
      "name": "Напиток Бланш Бир нефильтрованное",
      "description": null,
      "isParent": null,
      "hierarchicalId": 36,
      "hierarchicalParent": 32,
      "externalId": "72485158-6698-4a8f-abd3-48d2eec5beb9",
      "cost": 135,
      "unit": "кг",
      "balance": 49,
      "images": null,
    },
    {
      "name": "Напиток б/а  домашний",
      "description": null,
      "isParent": null,
      "hierarchicalId": 37,
      "hierarchicalParent": 32,
      "externalId": "19fae502-e8a9-499d-a03d-849c259b2b15",
      "cost": 103,
      "unit": "кг",
      "balance": 8.9,
      "images": null,
    },
    {
      "name": "Напиток Жигулевское особое светлое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 38,
      "hierarchicalParent": 32,
      "externalId": "687d481a-04a4-4ad3-bd69-3dbdb678eae2",
      "cost": 100,
      "unit": "кг",
      "balance": 145.5,
      "images": null,
    },
    {
      "name": "Напиток б/а Эль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 39,
      "hierarchicalParent": 32,
      "externalId": "d4e06a01-4712-49cb-85b8-53ffc20432da",
      "cost": 115,
      "unit": "кг",
      "balance": 57.5,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий",
      "description": null,
      "isParent": null,
      "hierarchicalId": 40,
      "hierarchicalParent": 32,
      "externalId": "74a87946-0d4e-4282-af33-17a735e57bf7",
      "cost": 108,
      "unit": "кг",
      "balance": 122,
      "images": null,
    },
    {
      "name": "Напиток б/а немецкий н/ф",
      "description": null,
      "isParent": null,
      "hierarchicalId": 41,
      "hierarchicalParent": 32,
      "externalId": "2476fa77-d2f7-42ee-b349-2623dce65230",
      "cost": 108,
      "unit": "кг",
      "balance": 98,
      "images": null,
    },
    {
      "name": "Напиток б/а СССР",
      "description": null,
      "isParent": null,
      "hierarchicalId": 42,
      "hierarchicalParent": 32,
      "externalId": "3bef03e6-84a5-47e4-9ec0-7651f6603b6b",
      "cost": 108,
      "unit": "кг",
      "balance": 34.7,
      "images": null,
    },
    {
      "name": "Напиток Чешский кабанчик пшеничное особое",
      "description": null,
      "isParent": null,
      "hierarchicalId": 43,
      "hierarchicalParent": 32,
      "externalId": "05aabb98-087f-4a53-bf2c-207ac8883544",
      "cost": 125,
      "unit": "кг",
      "balance": 57,
      "images": null,
    },
    {
      "name": "Напиток б/а чешский",
      "description": null,
      "isParent": null,
      "hierarchicalId": 44,
      "hierarchicalParent": 32,
      "externalId": "54d474ef-6d2d-42b8-8c8c-6887c9936ff5",
      "cost": 108,
      "unit": "кг",
      "balance": 100,
      "images": null,
    },
    {
      "name": "Напиток б/а Блэк беар",
      "description": null,
      "isParent": null,
      "hierarchicalId": 46,
      "hierarchicalParent": 32,
      "externalId": "b7ea3218-2b04-4a88-8255-63ec3af1a391",
      "cost": 145,
      "unit": "кг",
      "balance": 27.5,
      "images": null,
    },
    {
      "name": "Напиток б/а бойлерный",
      "description": null,
      "isParent": null,
      "hierarchicalId": 48,
      "hierarchicalParent": 32,
      "externalId": "7237ff6d-7d69-460a-b986-b356ae5e32be",
      "cost": 110,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а гранат",
      "description": null,
      "isParent": null,
      "hierarchicalId": 50,
      "hierarchicalParent": 33,
      "externalId": "672f18a6-c084-4b7e-8432-1be6eb46303d",
      "cost": 115,
      "unit": "кг",
      "balance": 24.3,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а клюква с брусникой",
      "description": null,
      "isParent": null,
      "hierarchicalId": 51,
      "hierarchicalParent": 33,
      "externalId": "baadfce9-1400-4b33-b98a-d566efc4eea7",
      "cost": 115,
      "unit": "кг",
      "balance": 30.6,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом апероль",
      "description": null,
      "isParent": null,
      "hierarchicalId": 53,
      "hierarchicalParent": 33,
      "externalId": "20305c85-358d-4b88-a632-28b6e2db53ae",
      "cost": 115,
      "unit": "кг",
      "balance": 0,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом асти роуз",
      "description": null,
      "isParent": null,
      "hierarchicalId": 54,
      "hierarchicalParent": 33,
      "externalId": "ea0cdecf-1896-4d66-b46f-758a31dbdf92",
      "cost": 115,
      "unit": "кг",
      "balance": 61.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом голубой лагуны",
      "description": null,
      "isParent": null,
      "hierarchicalId": 55,
      "hierarchicalParent": 33,
      "externalId": "9cb137dc-b9ff-4170-bcd9-d8024712b762",
      "cost": 115,
      "unit": "кг",
      "balance": 99.55,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом колы",
      "description": null,
      "isParent": null,
      "hierarchicalId": 56,
      "hierarchicalParent": 33,
      "externalId": "5d9c3596-0a06-4a60-8ed7-406acd6f80e6",
      "cost": 115,
      "unit": "кг",
      "balance": 61,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом мохито",
      "description": null,
      "isParent": null,
      "hierarchicalId": 57,
      "hierarchicalParent": 33,
      "externalId": "a4fbd31f-e6ad-41ad-aa0a-399d34169530",
      "cost": 115,
      "unit": "кг",
      "balance": 69.7,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом пина колады",
      "description": null,
      "isParent": null,
      "hierarchicalId": 58,
      "hierarchicalParent": 33,
      "externalId": "60af5b46-2996-4bf1-8476-2f73cdd23c5a",
      "cost": 115,
      "unit": "кг",
      "balance": 68.95,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом сакуры",
      "description": null,
      "isParent": null,
      "hierarchicalId": 59,
      "hierarchicalParent": 33,
      "externalId": "7ed7e67f-9cbf-47a3-bf93-9809d443e5ab",
      "cost": 115,
      "unit": "кг",
      "balance": 54,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом спелой маракуйи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 60,
      "hierarchicalParent": 33,
      "externalId": "58514c3c-5299-4f11-b81e-04665e38bf02",
      "cost": 115,
      "unit": "кг",
      "balance": 58,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а со вкусом яблоко",
      "description": null,
      "isParent": null,
      "hierarchicalId": 61,
      "hierarchicalParent": 33,
      "externalId": "2c8e242c-12d1-4a66-93b4-b701bd98cab5",
      "cost": 115,
      "unit": "кг",
      "balance": 38.5,
      "images": null,
    },
    {
      "name": "Фруктовый напиток б/а манговый смузи",
      "description": null,
      "isParent": null,
      "hierarchicalId": 62,
      "hierarchicalParent": 33,
      "externalId": "c95a4720-494c-4d09-a73f-cbf6e4314273",
      "cost": 115,
      "unit": "кг",
      "balance": 29,
      "images": null,
    },
    {
      "name": "Напиток  дюшес",
      "description": null,
      "isParent": null,
      "hierarchicalId": 65,
      "hierarchicalParent": 34,
      "externalId": "017fb7ab-1139-4e19-9513-873307ee8d9a",
      "cost": 60,
      "unit": "кг",
      "balance": 0.9,
      "images": null,
    },
    {
      "name": "Напиток  тархун",
      "description": null,
      "isParent": null,
      "hierarchicalId": 66,
      "hierarchicalParent": 34,
      "externalId": "1cb82518-c1c6-4197-b6cf-b428df109eca",
      "cost": 75,
      "unit": "кг",
      "balance": 51.2,
      "images": null,
    },
    {
      "name": "Напиток Квас",
      "description": null,
      "isParent": null,
      "hierarchicalId": 67,
      "hierarchicalParent": 34,
      "externalId": "d61fd7a9-8a7b-4355-9b20-b2920ff75f6f",
      "cost": 60,
      "unit": "л",
      "balance": 54.6,
      "images": null,
    },
    {
      "name": "Напиток Экстро Ситро",
      "description": null,
      "isParent": null,
      "hierarchicalId": 68,
      "hierarchicalParent": 34,
      "externalId": "565fb58b-e10d-4039-ae2b-23e88d5629ff",
      "cost": 60,
      "unit": "кг",
      "balance": 0,
      "images": null,
    }
  ]
}]
)